spring:
  application:
    name: loan-app
  cloud:
    config:
      label: 1.1
      profile: prod
      uri: http://localhost:8888     
name:
  app: Astha Yadav     
  
management:
  endpoints:
    web:
      exposure:
        include: "*"